[features]
seeds = true

[programs.localnet]
tipcoin = "BRTHhxE55gYbzhHtCaaRd6ngGL6j3pJHD4Pn4nBwJweh"

[programs.devnet]
tipcoin = "BRTHhxE55gYbzhHtCaaRd6ngGL6j3pJHD4Pn4nBwJweh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wareep/ItsACoin/solana/wallets/operator.json"

[scripts]
test = "pnpm run test:local"
